# Data
dataset_folder: /Users/egortimofeev/Data/tiny-imagenet-200
augmentations_p: 0.5
augmentations:
  Flip:
    p: 0.5
  Transpose:
    p: 0.1
  IAAAdditiveGaussianNoise:
    p: 0.3
  Blur:
    blur_limit: 5
    p: 0.5
  OpticalDistortion:
    p: 0.3

# Model
backbone: resnet18
use_pretrained: True

# Train settings
gpus:
epochs: 10

batch_size: 64
accum_steps: 1

learning_rate: 0.001
warmup_steps: 2000
patience_steps: 3
lr_reduce_factor: 0.5

grad_clip_thresh: 0.1
w_decay: 0.001
