# Data
dataset_folder: /Users/egortimofeev/Data/tiny-imagenet-200
augmentations_p: 0.5
augmentations:
  RandomSizedCrop:
    min_max_height: [32, 64]
    height: 64
    width: 64
    p: 0.5
  Rotate:
    limit: [-60, 60]
    p: 0.5
  VerticalFlip:
    p: 0.5
  HorizontalFlip:
    p: 0.5
  Blur:
    blur_limit: 3
    p: 0.3
  Solarize:
    p: 0.2
  GaussNoise:
    var_limit: 5
    p: 0.3

# Model
backbone: resnet18
use_pretrained: True

# Train settings
gpus:
epochs: 10

batch_size: 64
accum_steps: 1

learning_rate: 0.001
warmup_steps: 2000
patience_steps: 3
lr_reduce_factor: 0.5

grad_clip_thresh: 0.1
w_decay: 0.001
